title: SUNGH theme
description: This is a theme fit my own like. The origin version is Architect.
show_downloads: true
google_analytics:


url: "https://sungh.xyz"
baseurl: ""

title: "Guhao Sun"

comments:
  duoshuo:
    short_name: "sungh"